#!/usr/bin/env python3
"""Generate ds/source/font_data.c from the fonts in ds/third_party/fonts.

    python ds/tools/make_font.py

Needs Pillow (TTF rasterising). Fonts (licence texts in third_party/fonts/):
  - Pixel Operator / Pixel Operator Bold by Jayvee Enaguas, CC0 1.0
    (pixel font designed for 16 px, rasterised here without anti-aliasing)
  - Spleen 5x8 by Frederic Cambus, BSD 2-Clause (BDF bitmap font)

Each font becomes printable ASCII 32..126: a fixed cell height, a per-glyph
advance and one uint16_t per glyph row (bit 15 = leftmost pixel).
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
FONT_DIR = os.path.join(HERE, "..", "third_party", "fonts")
OUT = os.path.join(HERE, "..", "source", "font_data.c")
FIRST, LAST = 32, 126


def ttf_glyphs(path, size, top, height):
    """Rasterise a pixel TTF; rows top..top+height of the 16 px em box."""
    font = ImageFont.truetype(path, size)
    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = int(round(font.getlength(ch)))
        img = Image.new("1", (32, 32), 0)
        draw = ImageDraw.Draw(img)
        draw.fontmode = "1"
        draw.text((0, 0), ch, fill=1, font=font)
        rows = []
        for y in range(top, top + height):
            bits = 0
            for x in range(16):
                if img.getpixel((x, y)):
                    bits |= 0x8000 >> x
            rows.append(bits)
        # Nothing may be lost outside the cell
        for y in list(range(0, top)) + list(range(top + height, 32)):
            for x in range(32):
                if img.getpixel((x, y)):
                    sys.exit(f"{path}: {ch!r} has pixels outside the cell (row {y})")
        glyphs.append((adv, rows))
    return glyphs


def bdf_glyphs(path, height, ascent):
    """Read a BDF bitmap font into cells of `height` rows, baseline at `ascent`."""
    glyphs = {}
    with open(path, encoding="latin-1") as f:
        lines = iter(f.read().splitlines())
    for line in lines:
        if not line.startswith("STARTCHAR"):
            continue
        enc = adv = None
        bbx = None
        rows = []
        for line in lines:
            if line.startswith("ENCODING"):
                enc = int(line.split()[1])
            elif line.startswith("DWIDTH"):
                adv = int(line.split()[1])
            elif line.startswith("BBX"):
                bbx = [int(v) for v in line.split()[1:]]
            elif line == "BITMAP":
                for line in lines:
                    if line == "ENDCHAR":
                        break
                    rows.append(int(line, 16))
                break
        if enc is None or not FIRST <= enc <= LAST:
            continue
        w, h, xoff, yoff = bbx
        nbytes = (w + 7) // 8
        cell = [0] * height
        top = ascent - (h + yoff)
        for i, value in enumerate(rows):
            y = top + i
            if not 0 <= y < height:
                sys.exit(f"{path}: glyph {enc} outside the cell")
            bits = value << (16 - nbytes * 8)  # left-align in 16 bits
            cell[y] = (bits >> xoff) & 0xFFFF
        glyphs[enc] = (adv, cell)
    return [glyphs.get(c, (glyphs[63][0], glyphs[63][1])) for c in range(FIRST, LAST + 1)]


def emit(out, name, glyphs, height, baseline):
    out.append(f"static const uint8_t {name}_adv[] = {{")
    advs = [str(a) for a, _ in glyphs]
    for i in range(0, len(advs), 24):
        out.append("    " + ", ".join(advs[i:i + 24]) + ",")
    out.append("};")
    out.append(f"static const uint16_t {name}_rows[] = {{")
    for code, (_, rows) in zip(range(FIRST, LAST + 1), glyphs):
        label = chr(code) if chr(code) not in "\\" else "backslash"
        out.append("    " + ", ".join(f"0x{r:04X}" for r in rows) + f",  // {label}")
    out.append("};")
    out.append(f"const Font {name} = {{ {height}, {baseline}, {FIRST}, {LAST - FIRST + 1}, "
               f"{name}_adv, {name}_rows }};")
    out.append("")


def main():
    out = [
        "// Generated by ds/tools/make_font.py - do not edit.",
        "//",
        "// font_regular / font_bold: Pixel Operator by Jayvee Enaguas, CC0 1.0",
        "//   (public domain dedication), https://www.dafont.com/pixel-operator.font",
        "// font_mono: Spleen 5x8, Copyright (c) 2018-2026 Frederic Cambus,",
        "//   BSD 2-Clause, https://github.com/fcambus/spleen",
        "// Licence texts: ds/third_party/fonts/",
        "",
        '#include "gfx.h"',
        "",
    ]
    # Pixel Operator at 16 px: ink spans rows 2..14 of the em box, baseline row 13
    emit(out, "font_regular", ttf_glyphs(os.path.join(FONT_DIR, "PixelOperator.ttf"), 16, 2, 13), 13, 11)
    emit(out, "font_bold", ttf_glyphs(os.path.join(FONT_DIR, "PixelOperator-Bold.ttf"), 16, 2, 13), 13, 11)
    emit(out, "font_mono", bdf_glyphs(os.path.join(FONT_DIR, "spleen-5x8.bdf"), 8, 7), 8, 7)
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
