/* Generated by ps2/tools/gen_font.py - do not edit. */
#ifndef PS2SYNC_FONT_DATA_H
#define PS2SYNC_FONT_DATA_H

#include <stdint.h>

#define FONT_ATLAS_W     512
#define FONT_ATLAS_H     256
#define FONT_FIRST_CHAR  32
#define FONT_GLYPH_COUNT 95

typedef enum {
    FONT_TINY,
    FONT_SMALL,
    FONT_BODY,
    FONT_TITLE,
    FONT_HERO,
    FONT_COUNT
} FontId;

typedef struct {
    uint16_t x, y;      /* top-left in the atlas */
    uint8_t  w, h;      /* bitmap size */
    int8_t   xoff;      /* pen x -> bitmap left */
    int8_t   yoff;      /* baseline -> bitmap top (negative = above) */
    uint16_t adv_q;     /* advance in quarter pixels */
} FontGlyph;

typedef struct {
    uint8_t   size;     /* nominal pixel size */
    uint8_t   ascent;
    uint8_t   descent;
    FontGlyph glyphs[FONT_GLYPH_COUNT];
} FontFace;

extern const FontFace g_font_faces[FONT_COUNT];
/* 4-bit coverage, two pixels per byte, low nibble first. */
extern const uint8_t g_font_atlas4[FONT_ATLAS_W * FONT_ATLAS_H / 2];

#endif /* PS2SYNC_FONT_DATA_H */
