#ifndef PSPSYNC_FONT_H
#define PSPSYNC_FONT_H

/* Pre-rendered glyph atlas for the GU UI, generated by
 * psp/tools/make_font.py (Vegur, public domain).  The atlas is 8-bit
 * coverage; gui.c uploads it as a GU_PSM_T8 texture whose CLUT maps the
 * index to white with that alpha, so vertex colour tints the text. */

#include <stdint.h>

typedef struct {
    uint16_t x, y;      /* top-left in the atlas */
    uint8_t  w, h;      /* bitmap size (0 for blank glyphs) */
    int8_t   ox, oy;    /* bitmap offset from the pen on the baseline */
    uint8_t  adv;       /* horizontal advance */
} FontGlyph;

typedef struct {
    const FontGlyph *glyphs;   /* parallel to font_codepoints */
    int ascent;                /* baseline below the top of the line box */
    int line_h;
} FontFace;

extern const int      font_glyph_count;
extern const uint16_t font_codepoints[];   /* sorted ascending */

extern const FontFace font_small;   /* 12 px */
extern const FontFace font_body;    /* 13 px */
extern const FontFace font_bold;    /* 13 px semibold */
extern const FontFace font_title;   /* 17 px semibold */
extern const FontFace font_huge;    /* 30 px semibold, ASCII only */

extern const int     font_atlas_w;
extern const int     font_atlas_h;
extern const uint8_t font_atlas[];

#endif /* PSPSYNC_FONT_H */
