"""Add Wii U title IDs to the Wii U DAT, making it the single naming source.

Why
---
A Wii U save is keyed by its 16-hex title id (``0005000010143500``), whose low
word is not the product code — so the stock gametdb DAT, keyed by 4-char codes
(``ARDE``), cannot name a save at all.  Every client therefore had to carry its
own naming path (console meta.xml, a Cemu scan, a hand-written map).

wiiubrew's Title database publishes the missing column: title id ↔ product
code ↔ name.  This tool folds it into ``Nintendo - Wii U.dat`` as ``title_id``
lines — the same field the 3DS and Xbox DATs already use — so
``game_names.load_libretro_dat_to_dicts`` can resolve a Wii U save's name from
the id alone, on the server, with no client help.

What it writes
--------------
* For a DAT game whose ``serial`` matches a wiki product code, one
  ``title_id "…"`` line per id (a title can have several: revisions, demos).
* For wiki titles with no DAT entry at all (eShop apps, VC releases the DAT
  never covered), a minimal ``game ( name / serial / title_id )`` block, so the
  file really is complete rather than mostly complete.

Idempotent: existing ``title_id`` lines and previously appended blocks are
regenerated, so re-running after a DAT refresh just re-applies the mapping.

Usage
-----
    python tools/enrich_wiiu_dat_titleids.py                 # dry run
    python tools/enrich_wiiu_dat_titleids.py --apply
    python tools/enrich_wiiu_dat_titleids.py --wikitext copy.wiki --apply
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT / "tools"))

from wiiu_titles_from_wiiubrew import fetch_wikitext, parse_titles  # noqa: E402

DEFAULT_DAT = _REPO_ROOT / "server" / "data" / "dats" / "Nintendo - Wii U.dat"

# Marks the appended section so a re-run replaces it instead of duplicating it.
APPEND_HEADER = (
    "# ---- titles from wiiubrew Title_database with no DAT entry "
    "(generated by tools/enrich_wiiu_dat_titleids.py) ----"
)

_GAME_START_RE = re.compile(r"^game\s*\($")
_SERIAL_RE = re.compile(r'^\s*serial\s+"([^"]+)"')
_TITLE_ID_LINE_RE = re.compile(r'^\s*title_id\s+"[0-9A-Fa-f]{16}"\s*$')
_ROM_OPEN_RE = re.compile(r"^\s*rom\s*\(\s*$")


def _code_of(serial: str) -> str:
    """The 4-char key the DAT loader uses for a Wii U serial."""
    code = serial.strip().upper()
    return code[:4] if len(code) in (4, 6) and code.isalnum() else ""


def codes_to_title_ids(wiki: dict[str, tuple[str, str]]) -> dict[str, list[str]]:
    index: dict[str, list[str]] = {}
    for title_id, (_name, code) in sorted(wiki.items()):
        if code:
            index.setdefault(code, []).append(title_id)
    return index


def strip_generated(text: str) -> str:
    """Drop a previously appended block so re-runs stay idempotent."""
    idx = text.find(APPEND_HEADER)
    return text if idx < 0 else text[:idx].rstrip() + "\n"


def enrich(
    dat_text: str, wiki: dict[str, tuple[str, str]]
) -> tuple[str, int, int, list[str]]:
    """Return ``(new_text, games_tagged, ids_written, unmatched_title_ids)``."""
    by_code = codes_to_title_ids(wiki)
    seen_codes: set[str] = set()

    out: list[str] = []
    games_tagged = 0
    ids_written = 0

    # Per-game state.  ``serial`` is the game-level one: rom blocks repeat it,
    # and tagging inside a rom block would corrupt the entry.
    in_game = False
    in_rom = False
    game_lines: list[str] = []
    game_serial = ""
    # Index of the last GAME-level serial line.  A rom block repeats the
    # serial, and inserting after that one would bury the title id inside
    # ``rom ( … )`` where the DAT loader deliberately ignores everything.
    serial_line_idx = -1

    def flush_game() -> None:
        nonlocal games_tagged, ids_written, game_lines, game_serial, serial_line_idx
        code = _code_of(game_serial)
        title_ids = by_code.get(code, []) if code else []
        if code:
            seen_codes.add(code)

        if title_ids:
            # Keep the block reading name / serial / title_id, like the 3DS DAT.
            insert_at = serial_line_idx + 1 if serial_line_idx >= 0 else 1
            indent = "\t"
            m = re.match(r"^([ \t]+)", game_lines[insert_at - 1] if insert_at else "")
            if m:
                indent = m.group(1)
            lines = [f'{indent}title_id "{tid}"\n' for tid in title_ids]
            game_lines[insert_at:insert_at] = lines
            games_tagged += 1
            ids_written += len(title_ids)

        out.extend(game_lines)
        game_lines = []
        game_serial = ""
        serial_line_idx = -1

    for line in strip_generated(dat_text).splitlines(keepends=True):
        stripped = line.strip()

        if not in_game:
            if _GAME_START_RE.match(stripped):
                in_game = True
                in_rom = False
                game_lines = [line]
            else:
                out.append(line)
            continue

        # Inside a game block.
        if _TITLE_ID_LINE_RE.match(line):
            continue  # regenerated below

        game_lines.append(line)

        if in_rom:
            if stripped == ")":
                in_rom = False
            continue
        if _ROM_OPEN_RE.match(line):
            in_rom = True
            continue

        m = _SERIAL_RE.match(line)
        if m:
            # Not in a rom block here, so this is the game's own serial.
            serial_line_idx = len(game_lines) - 1
            if not game_serial:
                game_serial = m.group(1)
            continue

        if stripped == ")":
            in_game = False
            flush_game()

    if game_lines:  # truncated final block — keep it verbatim
        out.extend(game_lines)

    text = "".join(out)

    # Wiki titles the DAT has no entry for at all.
    unmatched = [
        tid
        for tid, (_name, code) in sorted(wiki.items())
        if not code or code not in seen_codes
    ]
    if unmatched:
        blocks = [f"\n{APPEND_HEADER}\n"]
        for tid in unmatched:
            name, code = wiki[tid]
            blocks.append("\ngame (\n")
            blocks.append(f'\tname "{name}"\n')
            if code:
                blocks.append(f'\tserial "{code}"\n')
            blocks.append(f'\ttitle_id "{tid}"\n')
            blocks.append(")\n")
        text = text.rstrip() + "\n" + "".join(blocks)
        ids_written += len(unmatched)

    return text, games_tagged, ids_written, unmatched


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dat", default=str(DEFAULT_DAT), help="DAT file to enrich")
    parser.add_argument("--wikitext", help="Parse a local copy instead of downloading")
    parser.add_argument("--apply", action="store_true", help="Write the DAT in place")
    args = parser.parse_args()

    dat_path = Path(args.dat)
    if not dat_path.is_file():
        print(f"error: {dat_path} not found")
        return 2

    if args.wikitext:
        wikitext = Path(args.wikitext).read_text(encoding="utf-8", errors="replace")
    else:
        print("Downloading wiiubrew Title_database")
        wikitext = fetch_wikitext()

    wiki = parse_titles(wikitext)
    print(f"Parsed {len(wiki)} game titles from the database")

    original = dat_path.read_text(encoding="utf-8", errors="replace")
    text, tagged, ids, unmatched = enrich(original, wiki)

    print(f"Tagged {tagged} existing DAT entries with {ids - len(unmatched)} title id(s)")
    print(f"Appended {len(unmatched)} title(s) the DAT had no entry for")

    if not args.apply:
        print("\nDry run — re-run with --apply to write.")
        return 0

    dat_path.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {dat_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
