#!/usr/bin/env python3
"""Rasterise the GameSync UI font into a C glyph atlas for the PS2 client.

The PS2 has no TrueType renderer worth linking, so the Vegur typeface
(Sora Sagano, public domain - the same file the Xbox client ships as
xbox/assets/font.ttf) is baked once, at a handful of pixel sizes, into an
anti-aliased coverage atlas.  ps2/source/gui.c expands it into a GS texture
at startup and draws each glyph as a textured sprite.

Output (both generated, committed so the build needs no Python):
    ps2/include/font_data.h   sizes, glyph metrics struct, extern decls
    ps2/source/font_data.c    metrics + 4-bit-per-pixel packed atlas

Run from the repo root:  python ps2/tools/gen_font.py
Requires Pillow.
"""

from __future__ import annotations

import os
import sys

from PIL import ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FONT_PATH = os.path.join(ROOT, "xbox", "assets", "font.ttf")
OUT_H = os.path.join(ROOT, "ps2", "include", "font_data.h")
OUT_C = os.path.join(ROOT, "ps2", "source", "font_data.c")

# (enum name, pixel size)
FACES = [
    ("FONT_TINY", 13),
    ("FONT_SMALL", 15),
    ("FONT_BODY", 18),
    ("FONT_TITLE", 23),
    ("FONT_HERO", 36),
]
FIRST_CHAR = 32
LAST_CHAR = 126
ATLAS_W = 512
PAD = 1


def build():
    glyphs = []  # per face: list of (mask, xoff, yoff, adv_q)
    faces = []
    for name, size in FACES:
        font = ImageFont.truetype(FONT_PATH, size)
        ascent, descent = font.getmetrics()
        items = []
        for code in range(FIRST_CHAR, LAST_CHAR + 1):
            ch = chr(code)
            mask, (ox, oy) = font.getmask2(ch, mode="L", anchor="ls")
            adv = font.getlength(ch)
            items.append((mask, ox, oy, int(round(adv * 4))))
        glyphs.append(items)
        faces.append((name, size, ascent, descent))

    # Shelf-pack every glyph of every face, tallest first.
    order = []
    for fi, items in enumerate(glyphs):
        for gi, (mask, *_rest) in enumerate(items):
            order.append((mask.size[1], mask.size[0], fi, gi))
    order.sort(key=lambda t: (-t[0], -t[1]))

    pos = {}
    x = y = shelf_h = 0
    for h, w, fi, gi in order:
        if w == 0 or h == 0:
            pos[(fi, gi)] = (0, 0)
            continue
        if x + w + PAD > ATLAS_W:
            x = 0
            y += shelf_h + PAD
            shelf_h = 0
        pos[(fi, gi)] = (x, y)
        x += w + PAD
        shelf_h = max(shelf_h, h)
    used_h = y + shelf_h
    atlas_h = 1
    while atlas_h < used_h:
        atlas_h *= 2
    if atlas_h > 512:
        sys.exit(f"atlas too tall: {used_h}")

    pixels = bytearray(ATLAS_W * atlas_h)
    for (fi, gi), (px, py) in pos.items():
        mask = glyphs[fi][gi][0]
        w, h = mask.size
        for row in range(h):
            for col in range(w):
                pixels[(py + row) * ATLAS_W + px + col] = mask.getpixel((col, row))

    # 4 bits per pixel, low nibble = left pixel.
    packed = bytearray(ATLAS_W * atlas_h // 2)
    for i in range(0, len(pixels), 2):
        a = (pixels[i] + 8) // 17
        b = (pixels[i + 1] + 8) // 17
        packed[i // 2] = (min(a, 15)) | (min(b, 15) << 4)

    return faces, glyphs, pos, atlas_h, packed, used_h


def write(faces, glyphs, pos, atlas_h, packed):
    count = LAST_CHAR - FIRST_CHAR + 1
    with open(OUT_H, "w", newline="\n") as f:
        f.write("/* Generated by ps2/tools/gen_font.py - do not edit. */\n")
        f.write("#ifndef PS2SYNC_FONT_DATA_H\n#define PS2SYNC_FONT_DATA_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define FONT_ATLAS_W     {ATLAS_W}\n")
        f.write(f"#define FONT_ATLAS_H     {atlas_h}\n")
        f.write(f"#define FONT_FIRST_CHAR  {FIRST_CHAR}\n")
        f.write(f"#define FONT_GLYPH_COUNT {count}\n\n")
        f.write("typedef enum {\n")
        for name, *_ in faces:
            f.write(f"    {name},\n")
        f.write("    FONT_COUNT\n} FontId;\n\n")
        f.write(
            "typedef struct {\n"
            "    uint16_t x, y;      /* top-left in the atlas */\n"
            "    uint8_t  w, h;      /* bitmap size */\n"
            "    int8_t   xoff;      /* pen x -> bitmap left */\n"
            "    int8_t   yoff;      /* baseline -> bitmap top (negative = above) */\n"
            "    uint16_t adv_q;     /* advance in quarter pixels */\n"
            "} FontGlyph;\n\n"
            "typedef struct {\n"
            "    uint8_t   size;     /* nominal pixel size */\n"
            "    uint8_t   ascent;\n"
            "    uint8_t   descent;\n"
            "    FontGlyph glyphs[FONT_GLYPH_COUNT];\n"
            "} FontFace;\n\n"
        )
        f.write("extern const FontFace g_font_faces[FONT_COUNT];\n")
        f.write("/* 4-bit coverage, two pixels per byte, low nibble first. */\n")
        f.write("extern const uint8_t g_font_atlas4[FONT_ATLAS_W * FONT_ATLAS_H / 2];\n\n")
        f.write("#endif /* PS2SYNC_FONT_DATA_H */\n")

    with open(OUT_C, "w", newline="\n") as f:
        f.write("/*\n * Generated by ps2/tools/gen_font.py - do not edit.\n *\n")
        f.write(" * Glyphs rasterised from the Vegur typeface by Sora Sagano\n")
        f.write(" * (public domain), xbox/assets/font.ttf.\n */\n\n")
        f.write('#include "font_data.h"\n\n')
        f.write("const FontFace g_font_faces[FONT_COUNT] = {\n")
        for fi, (name, size, ascent, descent) in enumerate(faces):
            f.write(f"    /* {name} */\n    {{ {size}, {ascent}, {descent}, {{\n")
            for gi, (mask, ox, oy, adv_q) in enumerate(glyphs[fi]):
                px, py = pos[(fi, gi)]
                w, h = mask.size
                ch = chr(FIRST_CHAR + gi)
                label = ch if ch not in "\\*/" else " "
                f.write(f"        {{ {px:3d}, {py:3d}, {w:2d}, {h:2d}, {ox:3d}, {oy:4d}, {adv_q:4d} }}, /* {label} */\n")
            f.write("    } },\n")
        f.write("};\n\n")
        f.write("const uint8_t g_font_atlas4[FONT_ATLAS_W * FONT_ATLAS_H / 2] = {\n")
        for i in range(0, len(packed), 24):
            chunk = packed[i:i + 24]
            f.write("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",\n")
        f.write("};\n")


def main():
    faces, glyphs, pos, atlas_h, packed, used_h = build()
    write(faces, glyphs, pos, atlas_h, packed)
    print(f"atlas {ATLAS_W}x{atlas_h} (used {used_h} rows), {len(packed)} bytes")


if __name__ == "__main__":
    main()
