#!/bin/bash
#
# Embed IRX modules as C byte arrays so the ELF is fully self-contained.
#
# Args:
#   $1  IRX source dir (typically $PS2SDK/iop/irx)
#   $2  Space-separated IRX filename list (e.g. "usbd.irx bdm.irx ...")
#   $3  Output .c path
#   $4  Output .h path
#
# Output format (per IRX):
#   const unsigned char <symbol>[] = { 0xXX, ... };
#   const unsigned int  <symbol>_size = sizeof(<symbol>);
#
# Symbol = filename without extension, dots → underscores.

set -e

IRX_DIR="$1"
IRX_LIST="$2"
OUT_C="$3"
OUT_H="$4"

mkdir -p "$(dirname "$OUT_C")" "$(dirname "$OUT_H")"

cat > "$OUT_H" <<EOF
/* Auto-generated by gen_irx_mods.sh — do not edit. */
#ifndef IRX_MODS_H
#define IRX_MODS_H

#ifdef __cplusplus
extern "C" {
#endif

EOF

cat > "$OUT_C" <<EOF
/* Auto-generated by gen_irx_mods.sh — do not edit. */
#include "irx_mods.h"

EOF

# List entries may be a bare filename (resolved against IRX_DIR) or a path
# containing '/' (used verbatim, for IRX outside the SDK tree like mmceman).
for irx in $IRX_LIST; do
    case "$irx" in
        */*) src="$irx";          base="$(basename "$irx")" ;;
        *)   src="$IRX_DIR/$irx";  base="$irx" ;;
    esac
    if [ ! -f "$src" ]; then
        echo "Missing IRX: $src" >&2
        exit 1
    fi
    sym="$(echo "$base" | sed 's/\./_/g')"

    {
        # 16-byte alignment is required by SifExecModuleBuffer — the
        # IOP-side load uses DMA which silently reads garbage from
        # unaligned source pointers, causing the IRX header check to
        # fail with E_LF_NOT_IRX (-201).
        printf 'const unsigned char %s[] __attribute__((aligned(16))) = {\n' "$sym"
        od -An -tx1 -v "$src" | awk '{
            for (i=1;i<=NF;i++) printf "0x%s,%s", $i, (i%16==0 ? "\n" : "")
        }'
        printf '\n};\n'
        printf 'const unsigned int %s_size = sizeof(%s);\n\n' "$sym" "$sym"
    } >> "$OUT_C"

    {
        printf 'extern const unsigned char %s[] __attribute__((aligned(16)));\n' "$sym"
        printf 'extern const unsigned int  %s_size;\n' "$sym"
    } >> "$OUT_H"
done

cat >> "$OUT_H" <<EOF

#ifdef __cplusplus
}
#endif

#endif /* IRX_MODS_H */
EOF

echo "Wrote $OUT_C and $OUT_H ($(echo $IRX_LIST | wc -w) modules)"
