#!/usr/bin/env python3
"""Generate psp/source/font_data.c, the anti-aliased glyph atlas of the PSP UI.

    python psp/tools/make_font.py

Needs Pillow. The typeface is Vegur by Sora Sagano (public domain), the same
file the Xbox client ships: xbox/assets/font.ttf.

Every face is rasterised into one 8-bit coverage atlas (512 px wide, uploaded
to the GE as a GU_PSM_T8 texture with a white-to-alpha CLUT), so text is a
single tinted sprite per glyph. Vegur only comes in one weight here; the
"bold" faces are rendered at 4x with a thin stroke and box-filtered down,
which reads as a semibold at these sizes.

Glyph set: printable ASCII, the Latin-1 letters Vegur has, and a few
typographic marks (dashes, quotes, ellipsis) — enough for game names.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
TTF = os.path.join(HERE, "..", "..", "xbox", "assets", "font.ttf")
OUT = os.path.join(HERE, "..", "source", "font_data.c")

ATLAS_W = 512
SS = 4  # supersampling factor for the faux-bold faces

# (C name, pixel size, bold, ASCII only).  The huge face only draws the
# splash wordmark and big counters, so it skips Latin-1 to keep the atlas
# at 512x256; its other glyphs are blank.
FACES = [
    ("small", 12, False, False),
    ("body", 13, False, False),
    ("bold", 13, True, False),
    ("title", 17, True, False),
    ("huge", 30, True, True),
]

# Code points Vegur lacks, drawn from another glyph moved up by a fraction
# of the pixel size: the middle dot is a raised period.
SYNTH = {0xB7: (".", 0.30)}

EXTRA = [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2026, 0x20AC]


def codepoints(font_path):
    from fontTools import ttLib  # only needed to read the cmap

    cmap = ttLib.TTFont(font_path).getBestCmap()
    cps = list(range(32, 127))
    cps += [c for c in range(0xA0, 0x100) if c in cmap]
    cps += [c for c in EXTRA if c in cmap]
    cps += [c for c in SYNTH if c not in cmap]
    return sorted(set(cps))


def render(path, size, bold, ch):
    """Return (coverage image, ox, oy, advance); ox/oy relative to the pen
    position on the baseline."""
    scale = SS if bold else 1
    font = ImageFont.truetype(path, size * scale)
    pad = 4 * scale
    asc, desc = font.getmetrics()
    w = int(font.getlength(ch)) + pad * 2 + 4 * scale
    h = asc + desc + pad * 2
    img = Image.new("L", (w, h), 0)
    draw = ImageDraw.Draw(img)
    stroke = scale // 2 if bold else 0
    draw.text((pad, pad + asc), ch, fill=255, font=font, anchor="ls",
              stroke_width=stroke, stroke_fill=255)
    adv = font.getlength(ch) / scale + (0.5 if bold else 0)
    if bold:
        img = img.resize((w // SS, h // SS), Image.BOX)
        pad //= SS
        asc = asc / SS
    bbox = img.getbbox()
    if bbox is None:
        return None, 0, 0, int(round(adv))
    # Keep a 1 px transparent border: sprites are never thinner than
    # 3 px, so the GE (and emulators) can't drop a 1 px wide '.' or 'i'.
    bbox = (bbox[0] - 1, bbox[1] - 1, bbox[2] + 1, bbox[3] + 1)
    glyph = img.crop(bbox)
    ox = bbox[0] - pad
    oy = bbox[1] - (pad + int(round(asc)))
    return glyph, ox, oy, int(round(adv))


def main():
    if not os.path.exists(TTF):
        sys.exit(f"missing {TTF}")
    cps = codepoints(TTF)

    faces = []
    for name, size, bold, ascii_only in FACES:
        font = ImageFont.truetype(TTF, size)
        asc, desc = font.getmetrics()
        glyphs = []
        for c in cps:
            if ascii_only and c > 126:
                glyphs.append((None, 0, 0, 0))
            elif c in SYNTH:
                src, lift = SYNTH[c]
                img, ox, oy, adv = render(TTF, size, bold, src)
                glyphs.append((img, ox, oy - int(round(size * lift)), adv))
            else:
                glyphs.append(render(TTF, size, bold, chr(c)))
        faces.append((name, asc, asc + desc, glyphs))

    # Shelf-pack every glyph of every face, tallest first
    items = []
    for fi, (_, _, _, glyphs) in enumerate(faces):
        for gi, (img, _, _, _) in enumerate(glyphs):
            if img is not None:
                items.append((img.size[1], img.size[0], fi, gi))
    items.sort(reverse=True)
    pos = {}
    x = y = shelf = 0
    for h, w, fi, gi in items:
        if x + w > ATLAS_W:
            x, y, shelf = 0, y + shelf, 0
        pos[(fi, gi)] = (x, y)
        x += w
        shelf = max(shelf, h)
    used_h = y + shelf
    atlas_h = 1
    while atlas_h < used_h:
        atlas_h *= 2
    if atlas_h > 512:
        sys.exit(f"atlas too tall ({used_h} px)")

    atlas = Image.new("L", (ATLAS_W, atlas_h), 0)
    for (fi, gi), (gx, gy) in pos.items():
        atlas.paste(faces[fi][3][gi][0], (gx, gy))

    out = []
    out.append("// Generated by psp/tools/make_font.py - do not edit.")
    out.append("//")
    out.append("// Vegur by Sora Sagano, public domain (same file as xbox/assets/font.ttf).")
    out.append("")
    out.append('#include "font.h"')
    out.append("")
    out.append(f"const int font_glyph_count = {len(cps)};")
    out.append("const uint16_t font_codepoints[] = {")
    for i in range(0, len(cps), 12):
        out.append("    " + ", ".join(f"0x{c:04X}" for c in cps[i:i + 12]) + ",")
    out.append("};")
    out.append("")
    for fi, (name, asc, line_h, glyphs) in enumerate(faces):
        out.append(f"static const FontGlyph glyphs_{name}[] = {{")
        for gi, (img, ox, oy, adv) in enumerate(glyphs):
            gx, gy = pos.get((fi, gi), (0, 0))
            gw, gh = img.size if img is not None else (0, 0)
            out.append(f"    {{{gx}, {gy}, {gw}, {gh}, {ox}, {oy}, {adv}}},")
        out.append("};")
        out.append(f"const FontFace font_{name} = {{glyphs_{name}, {asc}, {line_h}}};")
        out.append("")
    out.append(f"const int font_atlas_w = {ATLAS_W};")
    out.append(f"const int font_atlas_h = {atlas_h};")
    out.append(f"const uint8_t font_atlas[{ATLAS_W * atlas_h}] __attribute__((aligned(16))) = {{")
    data = atlas.tobytes()
    for i in range(0, len(data), 24):
        out.append("    " + ",".join(str(b) for b in data[i:i + 24]) + ",")
    out.append("};")
    out.append("")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {OUT}: {len(cps)} glyphs x {len(faces)} faces, atlas {ATLAS_W}x{atlas_h}")


if __name__ == "__main__":
    main()
